esphome:
  name: bad-infrarotheizung

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "55IQXLwU840p48qvpz1ASSb80vCyC6xlfg9mM0fFnEo="

ota:
  password: "b444809c8e00990ad6c2866235c2e8b7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.178.242
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.178.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bad-Infrarotheizung"
    password: "WjmFYyuIoLhj"

captive_portal:


i2c:
  sda: D2
  scl: D1
  scan: true


sensor:
  - platform: wifi_signal
    name: "bad-infrarotheizung_WiFi_Signal"
    update_interval: 30s
    entity_category: "diagnostic"
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 2
      - or:
          - delta: 2
          - throttle: 10min


  - platform: bme280
    address: 0x76
    
    update_interval: 1990ms  
    
    temperature:
      name: "Bad Temperatur"
      id: "bad_temp"
      filters:
        - or: 
          - delta: 0.2
          - throttle: 120sec
        
    pressure:
      name: "Bad Druck"
      id: "bad_press"
      accuracy_decimals: 3
      filters:
        - or: 
          - delta: 1
          - throttle: 120sec
        - sliding_window_moving_average:
            window_size: 8
            send_every: 4
            
    humidity:
      name: "Bad Feuchtigkeit"
      id: "bad_humid"
      filters:
        - or: 
          - delta: 1
          - throttle: 120sec

    
  - platform: template
    name: "Leistung Infraheizung"
    device_class: power 
    id: bad_power_heat
    lambda: |-
      if (id(switch_infrared).state) {
        return 1800;
      } else {
        return 0.0;
      }
    update_interval: 60s 
    unit_of_measurement: W

  - platform: total_daily_energy
    name: "Energie Infraheizung "
    power_id: bad_power_heat    
    filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
    unit_of_measurement: kWh 


time:
  - platform: homeassistant
    id: homeassistant_time     

binary_sensor:
  - platform: gpio
    pin:
      number: D0
    name: "Bad Tür"
    id: "bad_tuer"
    filters:
     - delayed_on: 10sec
    device_class: door     
    on_press:
    - climate.control:
       id: bad_thermostat_ir
       mode: "OFF"   

# Relais zu Schalten der Heizung
switch:
  - platform: gpio
    name: "Bad Schalter Infrarotheizung"
    id: switch_infrared
    pin:
      number: D7
      mode: OUTPUT
      inverted: True
    icon: "mdi:heat-wave"   
    restore_mode: ALWAYS_OFF 


# Einfaches Thermostat für Infrarotheizung
climate:
  - platform: thermostat
    name: "Bad Infrarotheizung"
    id: bad_thermostat_ir
    sensor: bad_temp
    default_target_temperature_low: 20 °C
    min_heating_off_time: 10s
    min_heating_run_time: 10s
    min_idle_time: 30s
    heat_action:
      - switch.turn_on: switch_infrared
    idle_action:
      - switch.turn_off: switch_infrared    